service: import-csv-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::import-csv-service"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::import-csv-service/*"

functions:
  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          path: /import
          method: GET
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: import-csv-service
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true